# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from connection import*


class Ui_Form(object): 
        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(398, 493)
                font = QtGui.QFont()
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                Form.setFont(font)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setGeometry(QtCore.QRect(0, 0, 400, 501))
                self.widget.setObjectName("widget")
                self.label = QtWidgets.QLabel(self.widget)
                self.label.setGeometry(QtCore.QRect(10, 10, 380, 471))
                font = QtGui.QFont()
                font.setPointSize(11)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.label.setFont(font)
                self.label.setStyleSheet("background-color:rgb(108, 122, 137);\n"
        "border-radius:10px;\n"
        "")
                self.label.setText("")
                self.label.setObjectName("label")
                self.username = QtWidgets.QLineEdit(self.widget)
                self.username.setGeometry(QtCore.QRect(70, 160, 270, 35))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.username.setFont(font)
                self.username.setAccessibleName("")
                self.username.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
        "background-color: rgba(0,0,0,0);\n"
        "border-bottom-color: rgba(42,82,101,255);\n"
        "color: rgb(255,255,255);\n"
        "padding-bottom: 7px;\n"
        "padding-left:15px")
                self.username.setText("")
                self.username.setEchoMode(QtWidgets.QLineEdit.Normal)
                self.username.setObjectName("username")
                self.password = QtWidgets.QLineEdit(self.widget)
                self.password.setGeometry(QtCore.QRect(70, 270, 270, 35))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.password.setFont(font)
                self.password.setAccessibleName("")
                self.password.setStyleSheet("border:2px solid rgba(0,0,0,0);\n"
        "background-color: rgba(0,0,0,0);\n"
        "border-bottom-color: rgba(42,82,101,255);\n"
        "color: rgb(255,255,255);\n"
        "padding-bottom: 7px;\n"
        "padding-left:15px")
                self.password.setText("")
                self.password.setEchoMode(QtWidgets.QLineEdit.Password)
                self.password.setObjectName("password")
                self.login_button = QtWidgets.QPushButton(self.widget)
                self.login_button.setGeometry(QtCore.QRect(40, 380, 311, 41))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(15)
                font.setBold(False)
                font.setItalic(False)
                font.setUnderline(False)
                font.setWeight(50)
                font.setKerning(True)
                self.login_button.setFont(font)
                self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
                self.login_button.setMouseTracking(True)
                self.login_button.setAccessibleName("")
                self.login_button.setStyleSheet("border-radius:5px;\n"
        "background-color: rgb(240,240,240);\n"
        "")
                self.login_button.setObjectName("login_button")
                self.label_2 = QtWidgets.QLabel(self.widget)
                self.label_2.setGeometry(QtCore.QRect(22, 155, 47, 41))
                self.label_2.setStyleSheet("")
                self.label_2.setText("")
                self.label_2.setPixmap(QtGui.QPixmap("img/picture2"))
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.widget)
                self.label_3.setGeometry(QtCore.QRect(22, 265, 47, 41))
                self.label_3.setText("")
                self.label_3.setPixmap(QtGui.QPixmap("img/picture3"))
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.widget)
                self.label_4.setGeometry(QtCore.QRect(10, 10, 380, 90))
                font = QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(20)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("border-top-left-radius:10px;\n"
        "border-top-right-radius:10px;\n"
        "background-color: rgb(240,240,240);\n"
        "border: 1px solid rgba(16,30,41,240);\n"
        "")
                self.label_4.setAlignment(QtCore.Qt.AlignCenter)
                self.label_4.setObjectName("label_4")
                self.groupBox = QtWidgets.QGroupBox(self.widget)
                self.groupBox.setGeometry(QtCore.QRect(70, 320, 211, 51))
                self.groupBox.setStyleSheet("border:none;")
                self.groupBox.setTitle("")
                self.groupBox.setObjectName("groupBox")

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)
                # gọi click
                self.login_button.clicked.connect(self.login) 

        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.username.setPlaceholderText(_translate("Form", "Nhập SĐT"))
                self.password.setPlaceholderText(_translate("Form", "Mật Khẩu"))
                self.login_button.setText(_translate("Form", "Log In"))
                self.label_4.setText(_translate("Form", "Đăng Nhập"))

       

        def login(self):
                username = self.username.text()
                password = self.password.text()
                if check_login(username, password):
                        QMessageBox.information(None, "Thông báo", "Đăng nhập thành công!")
                else:
                        QMessageBox.warning(None, "Cảnh báo", "Đăng nhập không thành công! Vui lòng kiểm tra lại số điện thoại và mật khẩu.")


def check_login(username, password):
        conn = connect_to_database()
        cursor = conn.cursor()

        cursor.execute("SELECT * FROM NhanVien WHERE SoDienThoai=%s AND Pass=%s", (username, password))
        employee = cursor.fetchone()
        
        
        if not employee:
                cursor.execute('SELECT * FROM KhachHang WHERE SoDienThoai=%s AND Pass=%s', (username, password))
                khachhang = cursor.fetchone()
        
        cursor.close()
        conn.close()

        if employee or khachhang:
                return True
        else:
                return False



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
